"""empty message

Revision ID: 5ba5ec86d15a
Revises: 
Create Date: 2019-12-22 17:47:38.272197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ba5ec86d15a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_mastery',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=True),
    sa.Column('student_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_mastery')
    # ### end Alembic commands ###
